name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
        with:
            parallel-commands-on-agents: |
                pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
    #                pnpm exec nx affected --target=package --parallel=2
    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
        with:
            number-of-agents: 3
